networks:
  board:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  backend:
    image: uniboard-backend:latest
    environment:
      DB_CONNECT: mongodb://10.5.0.3:27017
    ports:
      - 80:8080 # API
      - 81:8081 # Sockets
    networks:
      board:
        ipv4_address: 10.5.0.2
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      board:
        ipv4_address: 10.5.0.3